export const themeData = JSON.parse("{\"blog\":{},\"encrypt\":{\"config\":{\"/secret\":[\"$2a$10$2XxG7a5/tOWuZR36moIt8.LR7LMZVwd5d4X8X0eTU4q6FIxqtxZR2\"]}},\"pure\":false,\"darkmode\":\"switch\",\"themeColor\":{\"green\":\"#67c23a\",\"red\":\"#f26d6d\",\"red_\":\"#dd1370\",\"yellow\":\"#e3eca8\",\"orange\":\"#fb9b5f\",\"orange_\":\"#ff897d\"},\"fullscreen\":true,\"locales\":{\"/\":{\"blog\":{},\"repoDisplay\":true,\"navbarIcon\":true,\"navbarAutoHide\":\"mobile\",\"hideSiteNameonMobile\":true,\"sidebar\":[{\"text\":\"🎉文档\",\"prefix\":\"/docs/\",\"link\":\"/docs/\",\"collapsable\":true,\"children\":\"structure\"},{\"text\":\"🪂组件\",\"prefix\":\"/components/\",\"collapsable\":true,\"children\":\"structure\"},{\"text\":\"幻灯片\",\"prefix\":\"/exhibition\",\"link\":\"/exhibition\"}],\"sidebarIcon\":true,\"headerDepth\":2,\"lang\":\"zh-CN\",\"navbarLocales\":{\"langName\":\"简体中文\",\"selectLangText\":\"选择语言\",\"selectLangAriaLabel\":\"选择语言\"},\"metaLocales\":{\"author\":\"作者\",\"date\":\"写作日期\",\"origin\":\"原创\",\"views\":\"访问量\",\"category\":\"分类\",\"tag\":\"标签\",\"readingTime\":\"阅读时间\",\"words\":\"字数\",\"toc\":\"此页内容\",\"prev\":\"上一页\",\"next\":\"下一页\",\"lastUpdated\":\"上次编辑于\",\"contributors\":\"贡献者\",\"editLink\":\"编辑此页\"},\"blogLocales\":{\"article\":\"文章\",\"articleList\":\"文章列表\",\"category\":\"分类\",\"tag\":\"标签\",\"timeline\":\"时间轴\",\"timelineTitle\":\"昨日不在\",\"all\":\"全部\",\"intro\":\"个人介绍\",\"star\":\"收藏\",\"slides\":\"幻灯片\",\"encrypt\":\"加密\"},\"paginationLocales\":{\"prev\":\"上一页\",\"next\":\"下一页\",\"navigate\":\"跳转到\",\"action\":\"前往\",\"errorText\":\"请输入 1 到 $page 之前的页码！\"},\"outlookLocales\":{\"themeColor\":\"主题色\",\"darkmode\":\"外观\",\"fullscreen\":\"全屏\"},\"encryptLocales\":{\"title\":\"文章已加密\",\"placeholder\":\"输入密码\",\"remember\":\"记住密码\",\"errorHint\":\"请输入正确的密码\"},\"routeLocales\":{\"404msg\":[\"这里什么也没有\",\"我们是怎么来到这儿的？\",\"这 是 四 零 四 !\",\"看起来你访问了一个失效的链接\"],\"back\":\"返回上一页\",\"home\":\"带我回家\",\"openInNewWindow\":\"Open in new window\"},\"toc\":true,\"copyright\":false,\"editLink\":false,\"author\":{\"name\":\"📦\",\"url\":\"https://github.com/Kiyan-a\"},\"navbarLayout\":{\"left\":[\"Brand\"],\"center\":[\"Search\"],\"right\":[\"Links\",\"Language\",\"Outlook\",\"Repo\"]},\"logo\":\"/logo.svg\",\"repo\":\"https://github.com/Kiyan-a\",\"docsDir\":\"https://kiyan-a.github.io/sev/\",\"navbar\":[{\"text\":\"🎉文档\",\"link\":\"/docs/about\"},{\"text\":\"🪂组件\",\"prefix\":\"/components/\",\"children\":[{\"text\":\"文章 1\",\"icon\":\"edit\",\"link\":\"article1\"},{\"text\":\"文章 2\",\"icon\":\"edit\",\"link\":\"article2\"}]},{\"text\":\"🪵更新日志\",\"link\":\"/log/README.md\"}],\"displayFooter\":false,\"pageInfo\":false}}}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updateThemeData) {
    __VUE_HMR_RUNTIME__.updateThemeData(themeData)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ themeData }) => {
    __VUE_HMR_RUNTIME__.updateThemeData(themeData)
  })
}
