<template><div><h1 id="文件资源处理" tabindex="-1"><a class="header-anchor" href="#文件资源处理" aria-hidden="true">#</a> 文件资源处理</h1>
<p>前言：</p>
<p><strong>🪵Blob和File可以归为一类，它们都是数据</strong></p>
<p>📦<strong>formData是一个应用数据的场景</strong></p>
<p>使用场景：</p>
<p>图片、音视频、Excel等这几种常见的资源类型，如何从实现前端上传到服务器？</p>
<p>📝原生的 <strong>File</strong> 对象<code v-pre>new File(['&lt;h1&gt; Blob &lt;/h1&gt;'],'FileName',{...opytion})</code></p>
<ul>
<li>纯粹的文件，通常表示我们使用 <code v-pre>&lt;input type=&quot;file&quot;&gt;</code> 选择的 FileList 对象（<strong>没有经过任何处理的文件</strong>）</li>
<li>File 对象也是二进制对象，<strong>从属于 Blob</strong>；也就是说 <strong>File 是 Blob 里的一个小类</strong>，Blob 的属性和方法都可以用于 File，而 File 自己也<strong>有自己特有的属性和方法</strong>。对于 Blob 和 File 都有的属性，推荐使用 Blob 的属性</li>
</ul>
<p>📑转化后的 <strong>Blob</strong> 对象 <code v-pre>new Blob(['&lt;h1&gt; Blob &lt;/h1&gt;'],{...option})</code></p>
<ul>
<li>表示二进制大对象，<strong>并不是前端的特有对象</strong>，而是计算机界的通用术语，一个包含有<strong>只读原始数据</strong>的类文件对象（<strong>不可修改的二进制文件</strong>）</li>
<li>Blob只有一个slice方法，实现对文件的分割（注意这里并不违背Blob的只读性，<strong>slice只是复制指定范围内的Blob数据</strong>）<code v-pre>Blob.slice(start, end ,contentType)</code> （文件的断点续传利用了改特性）</li>
<li>例如，图片 canvas 合成后的 base64 转化为 Blob 对象，录音音频经过算法生成的数据转化 Bloab 对象等</li>
</ul>
<p>🗒️<strong>FormData 对象</strong><code v-pre>new FormData()</code></p>
<ul>
<li>使用 FormData 可以异步上传一个二进制文件，而这个二进制文件，就是上面讲的Blob对象</li>
<li>文件上传服务器时，FormData 就是封装的一个 form 表单，应用数据(Blob)的一个场景</li>
<li>给 FormData 对象添加一下文件的信息数据<code v-pre>new FormData().append('fileKey',file)</code>【formData 实例添加 file 对象】，然后通过1请求上传服务器</li>
</ul>
<p><strong>其它</strong>：</p>
<p>✍️<strong>图片链接转 base64</strong>（异步）</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="shiki" style="background-color: var(--shiki-color-background)"><code><span class="line"><span style="color: var(--shiki-token-comment)">/**</span></span>
<span class="line"><span style="color: var(--shiki-token-comment)">  *  url 转化 base64</span></span>
<span class="line"><span style="color: var(--shiki-token-comment)">  * </span><span style="color: var(--shiki-token-keyword)">@param</span><span style="color: var(--shiki-token-comment)"> </span><span style="color: var(--shiki-token-function)">{ Array }</span><span style="color: var(--shiki-token-comment)"> imageArr 图片链接</span></span>
<span class="line"><span style="color: var(--shiki-token-comment)">  * </span><span style="color: var(--shiki-token-keyword)">@return</span><span style="color: var(--shiki-token-comment)"> </span><span style="color: var(--shiki-token-function)">{ Promise }</span></span>
<span class="line"><span style="color: var(--shiki-token-comment)">  */</span></span>
<span class="line"><span style="color: var(--shiki-token-function)">transformationBase</span><span style="color: var(--shiki-color-text)">(imageArr) {</span></span>
<span class="line"><span style="color: var(--shiki-color-text)">    </span><span style="color: var(--shiki-token-keyword)">let</span><span style="color: var(--shiki-color-text)"> arr </span><span style="color: var(--shiki-token-keyword)">=</span><span style="color: var(--shiki-color-text)"> [];</span></span>
<span class="line"><span style="color: var(--shiki-color-text)">    </span><span style="color: var(--shiki-token-keyword)">return</span><span style="color: var(--shiki-color-text)"> </span><span style="color: var(--shiki-token-keyword)">new</span><span style="color: var(--shiki-color-text)"> </span><span style="color: var(--shiki-token-constant)">Promise</span><span style="color: var(--shiki-color-text)">((resolve) </span><span style="color: var(--shiki-token-keyword)">=&gt;</span><span style="color: var(--shiki-color-text)"> {</span></span>
<span class="line"><span style="color: var(--shiki-color-text)">        </span><span style="color: var(--shiki-token-constant)">imageArr</span><span style="color: var(--shiki-token-function)">.forEach</span><span style="color: var(--shiki-color-text)">((item) </span><span style="color: var(--shiki-token-keyword)">=&gt;</span><span style="color: var(--shiki-color-text)"> {</span></span>
<span class="line"><span style="color: var(--shiki-color-text)">            </span><span style="color: var(--shiki-token-keyword)">let</span><span style="color: var(--shiki-color-text)"> image </span><span style="color: var(--shiki-token-keyword)">=</span><span style="color: var(--shiki-color-text)"> </span><span style="color: var(--shiki-token-keyword)">new</span><span style="color: var(--shiki-color-text)"> </span><span style="color: var(--shiki-token-function)">Image</span><span style="color: var(--shiki-color-text)">();</span></span>
<span class="line"><span style="color: var(--shiki-color-text)">            </span><span style="color: var(--shiki-token-constant)">image</span><span style="color: var(--shiki-color-text)">.src </span><span style="color: var(--shiki-token-keyword)">=</span><span style="color: var(--shiki-color-text)"> item;</span></span>
<span class="line"><span style="color: var(--shiki-color-text)">            </span><span style="color: var(--shiki-token-constant)">image</span><span style="color: var(--shiki-token-function)">.setAttribute</span><span style="color: var(--shiki-color-text)">(</span><span style="color: var(--shiki-token-string-expression)">&#39;crossOrigin&#39;</span><span style="color: var(--shiki-token-punctuation)">,</span><span style="color: var(--shiki-color-text)"> </span><span style="color: var(--shiki-token-string-expression)">&#39;Anonymous&#39;</span><span style="color: var(--shiki-color-text)">);</span></span>
<span class="line"><span style="color: var(--shiki-color-text)">			</span></span>
<span class="line"><span style="color: var(--shiki-color-text)">            </span><span style="color: var(--shiki-token-constant)">image</span><span style="color: var(--shiki-color-text)">.</span><span style="color: var(--shiki-token-function)">onload</span><span style="color: var(--shiki-color-text)"> </span><span style="color: var(--shiki-token-keyword)">=</span><span style="color: var(--shiki-color-text)"> () </span><span style="color: var(--shiki-token-keyword)">=&gt;</span><span style="color: var(--shiki-color-text)"> {</span></span>
<span class="line"><span style="color: var(--shiki-color-text)">                </span><span style="color: var(--shiki-token-keyword)">let</span><span style="color: var(--shiki-color-text)"> canvas </span><span style="color: var(--shiki-token-keyword)">=</span><span style="color: var(--shiki-color-text)"> </span><span style="color: var(--shiki-token-constant)">document</span><span style="color: var(--shiki-token-function)">.createElement</span><span style="color: var(--shiki-color-text)">(</span><span style="color: var(--shiki-token-string-expression)">&#39;canvas&#39;</span><span style="color: var(--shiki-color-text)">);</span></span>
<span class="line"><span style="color: var(--shiki-color-text)">                </span><span style="color: var(--shiki-token-constant)">canvas</span><span style="color: var(--shiki-color-text)">.width </span><span style="color: var(--shiki-token-keyword)">=</span><span style="color: var(--shiki-color-text)"> </span><span style="color: var(--shiki-token-constant)">image</span><span style="color: var(--shiki-color-text)">.width;</span></span>
<span class="line"><span style="color: var(--shiki-color-text)">                </span><span style="color: var(--shiki-token-constant)">canvas</span><span style="color: var(--shiki-color-text)">.height </span><span style="color: var(--shiki-token-keyword)">=</span><span style="color: var(--shiki-color-text)"> </span><span style="color: var(--shiki-token-constant)">image</span><span style="color: var(--shiki-color-text)">.height;</span></span>
<span class="line"><span style="color: var(--shiki-color-text)">                </span><span style="color: var(--shiki-token-keyword)">let</span><span style="color: var(--shiki-color-text)"> ctx </span><span style="color: var(--shiki-token-keyword)">=</span><span style="color: var(--shiki-color-text)"> </span><span style="color: var(--shiki-token-constant)">canvas</span><span style="color: var(--shiki-token-function)">.getContext</span><span style="color: var(--shiki-color-text)">(</span><span style="color: var(--shiki-token-string-expression)">&#39;2d&#39;</span><span style="color: var(--shiki-color-text)">);</span></span>
<span class="line"><span style="color: var(--shiki-color-text)">                </span><span style="color: var(--shiki-token-constant)">ctx</span><span style="color: var(--shiki-token-function)">.drawImage</span><span style="color: var(--shiki-color-text)">(image</span><span style="color: var(--shiki-token-punctuation)">,</span><span style="color: var(--shiki-color-text)"> </span><span style="color: var(--shiki-token-constant)">0</span><span style="color: var(--shiki-token-punctuation)">,</span><span style="color: var(--shiki-color-text)"> </span><span style="color: var(--shiki-token-constant)">0</span><span style="color: var(--shiki-token-punctuation)">,</span><span style="color: var(--shiki-color-text)"> </span><span style="color: var(--shiki-token-constant)">image</span><span style="color: var(--shiki-color-text)">.width</span><span style="color: var(--shiki-token-punctuation)">,</span><span style="color: var(--shiki-color-text)"> </span><span style="color: var(--shiki-token-constant)">image</span><span style="color: var(--shiki-color-text)">.height);</span></span>
<span class="line"><span style="color: var(--shiki-color-text)">                </span><span style="color: var(--shiki-token-comment)">// 获取图片格式 png gif jpg...</span></span>
<span class="line"><span style="color: var(--shiki-color-text)">                </span><span style="color: var(--shiki-token-keyword)">let</span><span style="color: var(--shiki-color-text)"> ext </span><span style="color: var(--shiki-token-keyword)">=</span><span style="color: var(--shiki-color-text)"> </span><span style="color: var(--shiki-token-constant)">image</span><span style="color: var(--shiki-color-text)">.src</span></span>
<span class="line"><span style="color: var(--shiki-color-text)">                </span><span style="color: var(--shiki-token-function)">.substring</span><span style="color: var(--shiki-color-text)">(</span><span style="color: var(--shiki-token-constant)">image</span><span style="color: var(--shiki-token-function)">.</span><span style="color: var(--shiki-token-constant)">src</span><span style="color: var(--shiki-token-function)">.lastIndexOf</span><span style="color: var(--shiki-color-text)">(</span><span style="color: var(--shiki-token-string-expression)">&#39;.&#39;</span><span style="color: var(--shiki-color-text)">) </span><span style="color: var(--shiki-token-keyword)">+</span><span style="color: var(--shiki-color-text)"> </span><span style="color: var(--shiki-token-constant)">1</span><span style="color: var(--shiki-color-text)">)</span></span>
<span class="line"><span style="color: var(--shiki-color-text)">                </span><span style="color: var(--shiki-token-function)">.toLowerCase</span><span style="color: var(--shiki-color-text)">();</span></span>
<span class="line"><span style="color: var(--shiki-color-text)">                </span><span style="color: var(--shiki-token-comment)">// 转化方法 toDataURL(&#39;image/文件类型&#39;)</span></span>
<span class="line"><span style="color: var(--shiki-color-text)">                </span><span style="color: var(--shiki-token-keyword)">let</span><span style="color: var(--shiki-color-text)"> dataURL </span><span style="color: var(--shiki-token-keyword)">=</span><span style="color: var(--shiki-color-text)"> </span><span style="color: var(--shiki-token-constant)">canvas</span><span style="color: var(--shiki-token-function)">.toDataURL</span><span style="color: var(--shiki-color-text)">(</span><span style="color: var(--shiki-token-string-expression)">&#39;image/&#39;</span><span style="color: var(--shiki-color-text)"> </span><span style="color: var(--shiki-token-keyword)">+</span><span style="color: var(--shiki-color-text)"> ext);</span></span>
<span class="line"><span style="color: var(--shiki-color-text)">                </span><span style="color: var(--shiki-token-constant)">arr</span><span style="color: var(--shiki-token-function)">.push</span><span style="color: var(--shiki-color-text)">(dataURL);</span></span>
<span class="line"><span style="color: var(--shiki-color-text)">                </span><span style="color: var(--shiki-token-comment)">// 通过数组长度判断是否全部完成</span></span>
<span class="line"><span style="color: var(--shiki-color-text)">                </span><span style="color: var(--shiki-token-keyword)">if</span><span style="color: var(--shiki-color-text)"> (</span><span style="color: var(--shiki-token-constant)">arr</span><span style="color: var(--shiki-color-text)">.</span><span style="color: var(--shiki-token-constant)">length</span><span style="color: var(--shiki-color-text)"> </span><span style="color: var(--shiki-token-keyword)">==</span><span style="color: var(--shiki-color-text)"> </span><span style="color: var(--shiki-token-constant)">imageArr</span><span style="color: var(--shiki-color-text)">.</span><span style="color: var(--shiki-token-constant)">length</span><span style="color: var(--shiki-color-text)">) </span><span style="color: var(--shiki-token-function)">resolve</span><span style="color: var(--shiki-color-text)">(arr);</span></span>
<span class="line"><span style="color: var(--shiki-color-text)">            };</span></span>
<span class="line"><span style="color: var(--shiki-color-text)">        });</span></span>
<span class="line"><span style="color: var(--shiki-color-text)">    });</span></span>
<span class="line"><span style="color: var(--shiki-color-text)">}</span></span>
<span class="line"></span></code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p><strong>🎲文件转成 Base64</strong></p>
<blockquote>
<p>**FileReader：**前面提到 Blob对象是一个只读对象（二进制对象），直接读取只能拿到一堆0101二进制数据，因此需要借助专门的工具来读取，这个工具就是 FileReader。通过 FileReader 可以将 Blob 读取为不同的格式数据。（考虑兼容性问题）</p>
</blockquote>
<p>通过<code v-pre>FileReader.readAsDataURL(blob)</code> 就是将二进制数据读取并编码为 Base64 格式，<code v-pre>FileReader.readAsText(blob)</code> 就是将二进制数据读取并编码为字符串形式。</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="shiki" style="background-color: var(--shiki-color-background)"><code><span class="line"><span style="color: var(--shiki-token-comment)">/**</span></span>
<span class="line"><span style="color: var(--shiki-token-comment)">  *  文件 转成 Base64</span></span>
<span class="line"><span style="color: var(--shiki-token-comment)">  * </span><span style="color: var(--shiki-token-keyword)">@param</span><span style="color: var(--shiki-token-comment)"> </span><span style="color: var(--shiki-token-function)">{ Blob|file }</span><span style="color: var(--shiki-token-comment)"> file 文件</span></span>
<span class="line"><span style="color: var(--shiki-token-comment)">  * </span><span style="color: var(--shiki-token-keyword)">@return</span><span style="color: var(--shiki-token-comment)"> </span><span style="color: var(--shiki-token-function)">{ Promise }</span></span>
<span class="line"><span style="color: var(--shiki-token-comment)">  */</span></span>
<span class="line"><span style="color: var(--shiki-token-keyword)">function</span><span style="color: var(--shiki-color-text)"> </span><span style="color: var(--shiki-token-function)">readFile</span><span style="color: var(--shiki-color-text)">(file) {</span></span>
<span class="line"><span style="color: var(--shiki-color-text)">    retrun </span><span style="color: var(--shiki-token-keyword)">new</span><span style="color: var(--shiki-color-text)"> </span><span style="color: var(--shiki-token-constant)">Promise</span><span style="color: var(--shiki-color-text)">((resolve)</span><span style="color: var(--shiki-token-keyword)">=&gt;</span><span style="color: var(--shiki-color-text)">{</span></span>
<span class="line"><span style="color: var(--shiki-color-text)">        </span><span style="color: var(--shiki-token-keyword)">let</span><span style="color: var(--shiki-color-text)"> reader </span><span style="color: var(--shiki-token-keyword)">=</span><span style="color: var(--shiki-color-text)"> </span><span style="color: var(--shiki-token-keyword)">new</span><span style="color: var(--shiki-color-text)"> </span><span style="color: var(--shiki-token-function)">FileReader</span><span style="color: var(--shiki-color-text)">();</span></span>
<span class="line"><span style="color: var(--shiki-color-text)">        </span><span style="color: var(--shiki-token-constant)">reader</span><span style="color: var(--shiki-token-function)">.readAsDataURL</span><span style="color: var(--shiki-color-text)">(file);</span></span>
<span class="line"><span style="color: var(--shiki-color-text)">        </span><span style="color: var(--shiki-token-constant)">reader</span><span style="color: var(--shiki-color-text)">.</span><span style="color: var(--shiki-token-function)">onload</span><span style="color: var(--shiki-color-text)"> </span><span style="color: var(--shiki-token-keyword)">=</span><span style="color: var(--shiki-color-text)"> </span><span style="color: var(--shiki-token-keyword)">function</span><span style="color: var(--shiki-color-text)"> (e) { </span></span>
<span class="line"><span style="color: var(--shiki-color-text)">			</span><span style="color: var(--shiki-token-constant)">reader</span><span style="color: var(--shiki-color-text)">?.result </span><span style="color: var(--shiki-token-keyword)">&amp;&amp;</span><span style="color: var(--shiki-color-text)"> </span><span style="color: var(--shiki-token-function)">resolve</span><span style="color: var(--shiki-color-text)">(</span><span style="color: var(--shiki-token-constant)">reader</span><span style="color: var(--shiki-color-text)">.result)</span></span>
<span class="line"><span style="color: var(--shiki-color-text)">		}</span></span>
<span class="line"><span style="color: var(--shiki-color-text)">    })</span></span>
<span class="line"><span style="color: var(--shiki-color-text)">}</span></span>
<span class="line"></span></code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p><strong>🧷window.open下载</strong></p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="shiki" style="background-color: var(--shiki-color-background)"><code><span class="line"><span style="color: var(--shiki-token-comment)">/**</span></span>
<span class="line"><span style="color: var(--shiki-token-comment)">  * window.open下载</span></span>
<span class="line"><span style="color: var(--shiki-token-comment)">  * </span><span style="color: var(--shiki-token-keyword)">@param</span><span style="color: var(--shiki-token-comment)"> </span><span style="color: var(--shiki-token-function)">{ String }</span><span style="color: var(--shiki-token-comment)"> url 文件下载链接</span></span>
<span class="line"><span style="color: var(--shiki-token-comment)">  */</span></span>
<span class="line"><span style="color: var(--shiki-token-keyword)">function</span><span style="color: var(--shiki-color-text)"> </span><span style="color: var(--shiki-token-function)">downloadEvt</span><span style="color: var(--shiki-color-text)">(url) {</span></span>
<span class="line"><span style="color: var(--shiki-color-text)">      </span><span style="color: var(--shiki-token-constant)">window</span><span style="color: var(--shiki-token-function)">.open</span><span style="color: var(--shiki-color-text)">(url</span><span style="color: var(--shiki-token-punctuation)">,</span><span style="color: var(--shiki-color-text)"> </span><span style="color: var(--shiki-token-string-expression)">&#39;_self&#39;</span><span style="color: var(--shiki-color-text)">);</span></span>
<span class="line"><span style="color: var(--shiki-color-text)">}</span></span>
<span class="line"></span></code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p><strong>优点</strong></p>
<ul>
<li>简单方便直接</li>
</ul>
<p><strong>缺点</strong></p>
<ul>
<li>会出现URL长度限制问题</li>
<li>需要注意url编码问题</li>
<li>无法获取下载进度</li>
<li>无法在header中携带token做鉴权操作</li>
<li>无法直接下载浏览器可直接预览的文件类型（txt、png、pdf会直接预览）</li>
<li>无法判断接口是否返回成功</li>
</ul>
<p>🖇️<a href="https://blog.csdn.net/ljy123w/article/details/123438648" target="_blank" rel="noopener noreferrer">更多下载方法<ExternalLinkIcon/></a></p>
</div></template>
